-- Create Database
CREATE OR REPLACE DATABASE IOT_DB;

-- Use Database
USE DATABASE IOT_DB;

-- Use Default Schema
USE SCHEMA PUBLIC;

-- Create Sensor Data Table
CREATE OR REPLACE TABLE SENSOR_DATA (
    SENSOR_ID STRING,
    TEMPERATURE FLOAT,
    HUMIDITY FLOAT,
    PRESSURE FLOAT,
    AIR_QUALITY FLOAT,
    TIMESTAMP TIMESTAMP_NTZ
);